### ISSUE TITLE
NullPointerException - get table columns

### ISSUE THREAD

**Issue by Deathknorke** [sfa-siard/SiardGui#10]
It looks like there is a problem with views referencing other views in an access database.
The program throws a NullPointerException because it does not find the table.

To our database:

The first .accdb references a second .accdb.
The second one contains the tables.
In the first .accdb are the views. These reference each other and also tables from the second database.

Here the stacktrace:

```
ch.admin.bar.siard2.jdbc.AccessDatabaseMetaData.getColumns(AccessDatabaseMetaData.java:2512), 
	 ch.admin.bar.siard2.cmd.MetaDataFromDb.getColumns(MetaDataFromDb.java:444), 
	 ch.admin.bar.siard2.cmd.MetaDataFromDb.getViews(MetaDataFromDb.java:949), 
	 ch.admin.bar.siard2.cmd.MetaDataFromDb.getSchemaMetaData(MetaDataFromDb.java:1284), 
	 ch.admin.bar.siard2.cmd.MetaDataFromDb.download(MetaDataFromDb.java:1392), 
	 ch.admin.bar.siard2.gui.tasks.DownloadTask.call(DownloadTask.java:70), 
	 ch.admin.bar.siard2.gui.tasks.DownloadTask.call(DownloadTask.java:1), 
	 javafx.concurrent.Task$TaskCallable.call(Task.java:1423), 
	 java.util.concurrent.FutureTask.run(Unknown Source), 
	 java.lang.Thread.run(Unknown Source)
```

**Comment by HartwigThomas** [comment]
I agree, a NullPointerException should not happen. Can you attach the example?

**Comment by Deathknorke** [comment]
Hello, I'm sorry, i'm not allowed to share this .accdb file.

**Comment by HartwigThomas** [comment]
I created two accdb files - one with table and one with view referencing linked table.
I encountered a NullPointerException which was not really related to the linked table situation.
This problem is fixed in the current new release 2.1.112. Please verify whether this solves your problem and close the issue if it does. Otherwise I need a more precise test case.

**Comment by Deathknorke** [comment]
the error unfortunately still exists, I'll try to create a database with this error and send you the file

**Comment by Deathknorke** [comment]
here sample files. Please put the files to C:/temp/

[Database.zip](https://github.com/sfa-siard/SiardGui/files/3472145/Database.zip)

**Comment by HartwigThomas** [comment]
Thank you. I shall use this test case for diagnosis.

**Comment by Deathknorke** [comment]
Hi, is there any new information? :)

**Comment by HartwigThomas** [comment]
Hi, I was working on the integration of Postgres and have not yet gotten around to this issue.

**Comment by HartwigThomas** [comment]
I have been able to fix the problem with the help of your example. (Unfortunately MS Access is not documented, so you have to find out everything experimentally ...)

I shall publish the fixed version as a release in a few weeks when the Postgres driver is more "mature". You can compile SiardGui with the fix from the sources in the branch dev/enter, if your need is pressing.

**Comment by Deathknorke** [comment]
Hi, many thanks for the quick fix  :), I'll test it right away.

**Comment by Deathknorke** [comment]
unfortunately there is still an error in the original file. I'm trying to create a replica as close as possible to the original file.

sorry for the trouble

**Comment by Deathknorke** [comment]
[Database_frontend.zip](https://github.com/sfa-siard/SiardGui/files/3549371/Database_frontend.zip)

Here is a new version of the database. Please put the files to C:/temp/. 
I hope you can fix the problem with this.

**Comment by MartinR4838** [comment]
Hello, I did encounter same issue when testing export of ERMS from SQL Server 2014 express.

**Comment by MartinR4838** [comment]
Today I tried to produce SIARD with succes on other machine. Only difference was i5, 16GB RAM to i3, 4GB RAM. SQL server is in the same version.

**Comment by HartwigThomas** [comment]
@MartinR4838 : The issue you encountered is probably not the same as the MS Access one.
If you can make your issue reproduceable for me by sending me a database dump, a database schema, or the dump of a reduced copy of your database which still shows the error but does not contain any confidential data, please open an new issue.

**Comment by MartinR4838** [comment]
Thanks for reply, error is produced when user has only db_datareader role (as requests manual Introduction point 2.). User must be in db_dataowner role and than all runs.

**Comment by HartwigThomas** [comment]
@Deathknorke 
Your example helped me to fix another error (view based on view based on view ...).

Again you can compile SiardGui with the fix from the sources in the branch dev/enter, if your need is pressing. (I'll be off on vacation for a couple of weeks soon.)

**Comment by HartwigThomas** [comment]
@MartinR4838 If you can transmit a dump or the database schema, it might still be worth opening another issue. A permission problem should not result in a NullPointerException.

**Comment by Deathknorke** [comment]
@HartwigThomas there is another problem. Now I get the error message "Only one column with the same name allowed per table" (SiardApi/MetaVieImpl.java:283). 
 MetaVieImpl.java:283. 
In the view we have something like Table1.ID and Table2.ID, but the code removes the origin table. 
I think this is a bug too. 

best regards

**Comment by HartwigThomas** [comment]
The problem you describe may well be a bug. If you can make it reproduceable for me, please open another issue and close this one.
